#############################################################################
# Makefile for building: build/debug/qtimemage
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  qtimemage.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile qtimemage.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DDEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/debug -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtimemage1.0.0
DISTDIR = /home/jdr/Qt/qtimemage/build/debug/qtimemage1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/

####### Files

SOURCES       = ProjectComboBox.cpp \
		ProjectChooser.cpp \
		EventTreeWidget.cpp \
		MonthChooser.cpp \
		WeekChooser.cpp \
		ProjectTreeWidget.cpp \
		ClientTabBar.cpp \
		main.cpp \
		MainWindow.cpp \
		Client.cpp \
		DbRec.cpp \
		UnixSignals.cpp \
		ClientEditor.cpp \
		configItem.cpp \
		Global.cpp \
		MainToolBar.cpp \
		Project.cpp \
		ProjectPage.cpp \
		ProjectEditor.cpp \
		ClientPage.cpp \
		RateEditor.cpp \
		Event.cpp \
		Report.cpp \
		util.cpp build/debug/moc_ProjectComboBox.cpp \
		build/debug/moc_ProjectChooser.cpp \
		build/debug/moc_EventTreeWidget.cpp \
		build/debug/moc_MonthChooser.cpp \
		build/debug/moc_WeekChooser.cpp \
		build/debug/moc_ProjectTreeWidget.cpp \
		build/debug/moc_ClientTabBar.cpp \
		build/debug/moc_MainWindow.cpp \
		build/debug/moc_qtimemage.cpp \
		build/debug/moc_Client.cpp \
		build/debug/moc_UnixSignals.cpp \
		build/debug/moc_ClientEditor.cpp \
		build/debug/moc_MainToolBar.cpp \
		build/debug/moc_Project.cpp \
		build/debug/moc_ProjectPage.cpp \
		build/debug/moc_ProjectEditor.cpp \
		build/debug/moc_ClientPage.cpp \
		build/debug/moc_RateEditor.cpp \
		build/debug/moc_Event.cpp \
		build/debug/moc_Report.cpp
OBJECTS       = build/debug/ProjectComboBox.o \
		build/debug/ProjectChooser.o \
		build/debug/EventTreeWidget.o \
		build/debug/MonthChooser.o \
		build/debug/WeekChooser.o \
		build/debug/ProjectTreeWidget.o \
		build/debug/ClientTabBar.o \
		build/debug/main.o \
		build/debug/MainWindow.o \
		build/debug/Client.o \
		build/debug/DbRec.o \
		build/debug/UnixSignals.o \
		build/debug/ClientEditor.o \
		build/debug/configItem.o \
		build/debug/Global.o \
		build/debug/MainToolBar.o \
		build/debug/Project.o \
		build/debug/ProjectPage.o \
		build/debug/ProjectEditor.o \
		build/debug/ClientPage.o \
		build/debug/RateEditor.o \
		build/debug/Event.o \
		build/debug/Report.o \
		build/debug/util.o \
		build/debug/moc_ProjectComboBox.o \
		build/debug/moc_ProjectChooser.o \
		build/debug/moc_EventTreeWidget.o \
		build/debug/moc_MonthChooser.o \
		build/debug/moc_WeekChooser.o \
		build/debug/moc_ProjectTreeWidget.o \
		build/debug/moc_ClientTabBar.o \
		build/debug/moc_MainWindow.o \
		build/debug/moc_qtimemage.o \
		build/debug/moc_Client.o \
		build/debug/moc_UnixSignals.o \
		build/debug/moc_ClientEditor.o \
		build/debug/moc_MainToolBar.o \
		build/debug/moc_Project.o \
		build/debug/moc_ProjectPage.o \
		build/debug/moc_ProjectEditor.o \
		build/debug/moc_ClientPage.o \
		build/debug/moc_RateEditor.o \
		build/debug/moc_Event.o \
		build/debug/moc_Report.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qtimemage.pro ProjectComboBox.h \
		ProjectChooser.h \
		EventTreeWidget.h \
		MonthChooser.h \
		WeekChooser.h \
		ProjectTreeWidget.h \
		ClientTabBar.h \
		MainWindow.h \
		qtimemage.h \
		Client.h \
		DbRec.h \
		UnixSignals.h \
		ClientEditor.h \
		configItem.h \
		MainToolBar.h \
		Project.h \
		ProjectPage.h \
		ProjectEditor.h \
		ClientPage.h \
		RateEditor.h \
		Event.h \
		Report.h ProjectComboBox.cpp \
		ProjectChooser.cpp \
		EventTreeWidget.cpp \
		MonthChooser.cpp \
		WeekChooser.cpp \
		ProjectTreeWidget.cpp \
		ClientTabBar.cpp \
		main.cpp \
		MainWindow.cpp \
		Client.cpp \
		DbRec.cpp \
		UnixSignals.cpp \
		ClientEditor.cpp \
		configItem.cpp \
		Global.cpp \
		MainToolBar.cpp \
		Project.cpp \
		ProjectPage.cpp \
		ProjectEditor.cpp \
		ClientPage.cpp \
		RateEditor.cpp \
		Event.cpp \
		Report.cpp \
		util.cpp
QMAKE_TARGET  = qtimemage
DESTDIR       = build/debug/
TARGET        = build/debug/qtimemage


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtimemage.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qtimemage.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile qtimemage.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qtimemage.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qtimemage.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ProjectComboBox.h ProjectChooser.h EventTreeWidget.h MonthChooser.h WeekChooser.h ProjectTreeWidget.h ClientTabBar.h MainWindow.h qtimemage.h Client.h DbRec.h UnixSignals.h ClientEditor.h configItem.h MainToolBar.h Project.h ProjectPage.h ProjectEditor.h ClientPage.h RateEditor.h Event.h Report.h $(DISTDIR)/
	$(COPY_FILE) --parents ProjectComboBox.cpp ProjectChooser.cpp EventTreeWidget.cpp MonthChooser.cpp WeekChooser.cpp ProjectTreeWidget.cpp ClientTabBar.cpp main.cpp MainWindow.cpp Client.cpp DbRec.cpp UnixSignals.cpp ClientEditor.cpp configItem.cpp Global.cpp MainToolBar.cpp Project.cpp ProjectPage.cpp ProjectEditor.cpp ClientPage.cpp RateEditor.cpp Event.cpp Report.cpp util.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/debug/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/debug/moc_predefs.h
build/debug/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -dM -E -o build/debug/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/debug/moc_ProjectComboBox.cpp build/debug/moc_ProjectChooser.cpp build/debug/moc_EventTreeWidget.cpp build/debug/moc_MonthChooser.cpp build/debug/moc_WeekChooser.cpp build/debug/moc_ProjectTreeWidget.cpp build/debug/moc_ClientTabBar.cpp build/debug/moc_MainWindow.cpp build/debug/moc_qtimemage.cpp build/debug/moc_Client.cpp build/debug/moc_UnixSignals.cpp build/debug/moc_ClientEditor.cpp build/debug/moc_MainToolBar.cpp build/debug/moc_Project.cpp build/debug/moc_ProjectPage.cpp build/debug/moc_ProjectEditor.cpp build/debug/moc_ClientPage.cpp build/debug/moc_RateEditor.cpp build/debug/moc_Event.cpp build/debug/moc_Report.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/moc_ProjectComboBox.cpp build/debug/moc_ProjectChooser.cpp build/debug/moc_EventTreeWidget.cpp build/debug/moc_MonthChooser.cpp build/debug/moc_WeekChooser.cpp build/debug/moc_ProjectTreeWidget.cpp build/debug/moc_ClientTabBar.cpp build/debug/moc_MainWindow.cpp build/debug/moc_qtimemage.cpp build/debug/moc_Client.cpp build/debug/moc_UnixSignals.cpp build/debug/moc_ClientEditor.cpp build/debug/moc_MainToolBar.cpp build/debug/moc_Project.cpp build/debug/moc_ProjectPage.cpp build/debug/moc_ProjectEditor.cpp build/debug/moc_ClientPage.cpp build/debug/moc_RateEditor.cpp build/debug/moc_Event.cpp build/debug/moc_Report.cpp
build/debug/moc_ProjectComboBox.cpp: ProjectComboBox.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjectComboBox.h -o build/debug/moc_ProjectComboBox.cpp

build/debug/moc_ProjectChooser.cpp: ProjectChooser.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjectChooser.h -o build/debug/moc_ProjectChooser.cpp

build/debug/moc_EventTreeWidget.cpp: EventTreeWidget.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include EventTreeWidget.h -o build/debug/moc_EventTreeWidget.cpp

build/debug/moc_MonthChooser.cpp: MonthChooser.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MonthChooser.h -o build/debug/moc_MonthChooser.cpp

build/debug/moc_WeekChooser.cpp: WeekChooser.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include WeekChooser.h -o build/debug/moc_WeekChooser.cpp

build/debug/moc_ProjectTreeWidget.cpp: ProjectTreeWidget.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjectTreeWidget.h -o build/debug/moc_ProjectTreeWidget.cpp

build/debug/moc_ClientTabBar.cpp: ClientTabBar.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClientTabBar.h -o build/debug/moc_ClientTabBar.cpp

build/debug/moc_MainWindow.cpp: MainWindow.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o build/debug/moc_MainWindow.cpp

build/debug/moc_qtimemage.cpp: Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		qtimemage.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include qtimemage.h -o build/debug/moc_qtimemage.cpp

build/debug/moc_Client.cpp: DbRec.h \
		Client.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Client.h -o build/debug/moc_Client.cpp

build/debug/moc_UnixSignals.cpp: UnixSignals.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UnixSignals.h -o build/debug/moc_UnixSignals.cpp

build/debug/moc_ClientEditor.cpp: ClientEditor.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClientEditor.h -o build/debug/moc_ClientEditor.cpp

build/debug/moc_MainToolBar.cpp: MainToolBar.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainToolBar.h -o build/debug/moc_MainToolBar.cpp

build/debug/moc_Project.cpp: DbRec.h \
		Event.h \
		Project.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Project.h -o build/debug/moc_Project.cpp

build/debug/moc_ProjectPage.cpp: qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		ProjectPage.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjectPage.h -o build/debug/moc_ProjectPage.cpp

build/debug/moc_ProjectEditor.cpp: ProjectEditor.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjectEditor.h -o build/debug/moc_ProjectEditor.cpp

build/debug/moc_ClientPage.cpp: qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		ClientPage.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClientPage.h -o build/debug/moc_ClientPage.cpp

build/debug/moc_RateEditor.cpp: RateEditor.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include RateEditor.h -o build/debug/moc_RateEditor.cpp

build/debug/moc_Event.cpp: DbRec.h \
		Event.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Event.h -o build/debug/moc_Event.cpp

build/debug/moc_Report.cpp: Report.h \
		build/debug/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jdr/Qt/qtimemage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Report.h -o build/debug/moc_Report.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/debug/ProjectComboBox.o: ProjectComboBox.cpp configItem.h \
		ProjectComboBox.h \
		qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ProjectComboBox.o ProjectComboBox.cpp

build/debug/ProjectChooser.o: ProjectChooser.cpp util.h \
		configItem.h \
		qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		ProjectChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ProjectChooser.o ProjectChooser.cpp

build/debug/EventTreeWidget.o: EventTreeWidget.cpp Event.h \
		DbRec.h \
		EventTreeWidget.h \
		MainWindow.h \
		ProjectChooser.h \
		qtimemage.h \
		Client.h \
		Project.h \
		Report.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/EventTreeWidget.o EventTreeWidget.cpp

build/debug/MonthChooser.o: MonthChooser.cpp util.h \
		MonthChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/MonthChooser.o MonthChooser.cpp

build/debug/WeekChooser.o: WeekChooser.cpp util.h \
		WeekChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/WeekChooser.o WeekChooser.cpp

build/debug/ProjectTreeWidget.o: ProjectTreeWidget.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		util.h \
		Report.h \
		ProjectTreeWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ProjectTreeWidget.o ProjectTreeWidget.cpp

build/debug/ClientTabBar.o: ClientTabBar.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		ClientTabBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ClientTabBar.o ClientTabBar.cpp

build/debug/main.o: main.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		MainWindow.h \
		UnixSignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/main.o main.cpp

build/debug/MainWindow.o: MainWindow.cpp Client.h \
		DbRec.h \
		ClientPage.h \
		qtimemage.h \
		Project.h \
		Event.h \
		ClientTabBar.h \
		configItem.h \
		MainToolBar.h \
		MainWindow.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/MainWindow.o MainWindow.cpp

build/debug/Client.o: Client.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/Client.o Client.cpp

build/debug/DbRec.o: DbRec.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/DbRec.o DbRec.cpp

build/debug/UnixSignals.o: UnixSignals.cpp UnixSignals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/UnixSignals.o UnixSignals.cpp

build/debug/ClientEditor.o: ClientEditor.cpp Client.h \
		DbRec.h \
		RateEditor.h \
		ClientEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ClientEditor.o ClientEditor.cpp

build/debug/configItem.o: configItem.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		configItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/configItem.o configItem.cpp

build/debug/Global.o: Global.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		MainWindow.h \
		configItem.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/Global.o Global.cpp

build/debug/MainToolBar.o: MainToolBar.cpp ClientEditor.h \
		Client.h \
		DbRec.h \
		configItem.h \
		MainToolBar.h \
		MainWindow.h \
		ProjectChooser.h \
		ProjectComboBox.h \
		qtimemage.h \
		Project.h \
		Event.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/MainToolBar.o MainToolBar.cpp

build/debug/Project.o: Project.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/Project.o Project.cpp

build/debug/ProjectPage.o: ProjectPage.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		EventTreeWidget.h \
		ProjectEditor.h \
		configItem.h \
		util.h \
		ProjectPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ProjectPage.o ProjectPage.cpp

build/debug/ProjectEditor.o: ProjectEditor.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		RateEditor.h \
		ProjectEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ProjectEditor.o ProjectEditor.cpp

build/debug/ClientPage.o: ClientPage.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		ProjectTreeWidget.h \
		Report.h \
		ProjectEditor.h \
		ProjectPage.h \
		configItem.h \
		util.h \
		WeekChooser.h \
		MonthChooser.h \
		ClientPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/ClientPage.o ClientPage.cpp

build/debug/RateEditor.o: RateEditor.cpp RateEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/RateEditor.o RateEditor.cpp

build/debug/Event.o: Event.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/Event.o Event.cpp

build/debug/Report.o: Report.cpp qtimemage.h \
		Client.h \
		DbRec.h \
		Project.h \
		Event.h \
		util.h \
		configItem.h \
		Report.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/Report.o Report.cpp

build/debug/util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/util.o util.cpp

build/debug/moc_ProjectComboBox.o: build/debug/moc_ProjectComboBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ProjectComboBox.o build/debug/moc_ProjectComboBox.cpp

build/debug/moc_ProjectChooser.o: build/debug/moc_ProjectChooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ProjectChooser.o build/debug/moc_ProjectChooser.cpp

build/debug/moc_EventTreeWidget.o: build/debug/moc_EventTreeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_EventTreeWidget.o build/debug/moc_EventTreeWidget.cpp

build/debug/moc_MonthChooser.o: build/debug/moc_MonthChooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_MonthChooser.o build/debug/moc_MonthChooser.cpp

build/debug/moc_WeekChooser.o: build/debug/moc_WeekChooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_WeekChooser.o build/debug/moc_WeekChooser.cpp

build/debug/moc_ProjectTreeWidget.o: build/debug/moc_ProjectTreeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ProjectTreeWidget.o build/debug/moc_ProjectTreeWidget.cpp

build/debug/moc_ClientTabBar.o: build/debug/moc_ClientTabBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ClientTabBar.o build/debug/moc_ClientTabBar.cpp

build/debug/moc_MainWindow.o: build/debug/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_MainWindow.o build/debug/moc_MainWindow.cpp

build/debug/moc_qtimemage.o: build/debug/moc_qtimemage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_qtimemage.o build/debug/moc_qtimemage.cpp

build/debug/moc_Client.o: build/debug/moc_Client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_Client.o build/debug/moc_Client.cpp

build/debug/moc_UnixSignals.o: build/debug/moc_UnixSignals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_UnixSignals.o build/debug/moc_UnixSignals.cpp

build/debug/moc_ClientEditor.o: build/debug/moc_ClientEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ClientEditor.o build/debug/moc_ClientEditor.cpp

build/debug/moc_MainToolBar.o: build/debug/moc_MainToolBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_MainToolBar.o build/debug/moc_MainToolBar.cpp

build/debug/moc_Project.o: build/debug/moc_Project.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_Project.o build/debug/moc_Project.cpp

build/debug/moc_ProjectPage.o: build/debug/moc_ProjectPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ProjectPage.o build/debug/moc_ProjectPage.cpp

build/debug/moc_ProjectEditor.o: build/debug/moc_ProjectEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ProjectEditor.o build/debug/moc_ProjectEditor.cpp

build/debug/moc_ClientPage.o: build/debug/moc_ClientPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_ClientPage.o build/debug/moc_ClientPage.cpp

build/debug/moc_RateEditor.o: build/debug/moc_RateEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_RateEditor.o build/debug/moc_RateEditor.cpp

build/debug/moc_Event.o: build/debug/moc_Event.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_Event.o build/debug/moc_Event.cpp

build/debug/moc_Report.o: build/debug/moc_Report.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/moc_Report.o build/debug/moc_Report.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

